<?php
// src/AppBundle/Entity/Repository/IndicatorRepository.php
namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IndicatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicatorRepository extends EntityRepository
{
}
