imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    # Bundles config
    - { resource: config_stof.yml }
    - { resource: config_sonata_admin.yml }
    - { resource: config_vich.yml }
    - { resource: config_liip.yml }
    - { resource: config_formatter.yml }
    # Services
    - { resource: @MenuBundle/Menu/config/servicesMenu.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/common/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    # Twig globals!!!
    globals:
        global_paypal:            "%paypal%"
        global_personal_links:    "%personal_links%"
        global_developers_agency: "%developers_agency%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AppBundle, TwigBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    app.page_init_listener:
        class:     AppBundle\EventListener\PageInitListener
        scope:     request
        arguments: [ "@request", "@app.metadata" ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    app.metadata:
        class: AppBundle\Service\Metadata
        arguments:
            - "@doctrine.orm.entity_manager"

    app.mailer_shortcut:
        class: AppBundle\Service\MailerShortcut
        arguments:
            - "@mailer"

    app.ipn_handler:
        class: AppBundle\Service\Payment\IPNHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%paypal%"