app:
    resource: "@AppBundle/Controller/"
    type:     annotation

sonata_user_profile_show:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /admin

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /admin
    defaults:
        _locale: "%locale%"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"